name: MLflow Training Workflow

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Menggunakan file conda.yaml yang kamu tunjukkan
          environment-file: conda.yaml 
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Run modelling
        # PENTING: Harus pakai shell bash -l {0} agar conda aktif
        shell: bash -l {0}
        run: |
          conda info
          conda list
          # Jalankan mlflow dengan env-manager local karena conda sudah disiapkan di atas
          mlflow run . --env-manager=local

