name: Retrain ML Model

on: [push]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: 3.10

    - name: Install mlflow
      run: |
        pip install mlflow

    - name: Run modelling
      run: mlflow run MLProject -e modelling

    - name: Run tuning
      run: mlflow run MLProject -e tuning
